### ISSUE TITLE
produce() raises KafkaError{code=_UNKNOWN_TOPIC,val=-188,str="Unable to produce message: Local: Unknown topic"}

### ISSUE THREAD

**Issue by fillest** [confluentinc/confluent-kafka-python#102]
confluent-kafka==0.9.2, librdkafka 0.9.2, kafka 0.10.1.0, Python 2.7.6

I run 3 AWS instances with kafka brokers and zookepers. Each topic has 1 partition and replication factor 3. Producers (web apps) run continuously (except periodic autorestarting) on other instances and on app start each one gets bootstrap.servers set to a list of current kafka instance IPs.
Sometimes I need to recreate one of these instances. I stop kafka server, then zookeeper, then terminate the instance. ISR shrinks to 2 as expected and so on (`kafka-topics.sh --describe`). Producer gets mad though (not sure if always or only when this instance was the topic leader) and for some period raises:
```
...
    _producer.produce(topic, cPickle.dumps(value, KAFKA_PICKLE_PROTO))
KafkaException: KafkaError{code=_UNKNOWN_TOPIC,val=-188,str="Unable to produce message: Local: Unknown topic"}
```
Obviously, it results in losing these messages. How to avoid it (except catching it and retrying in a blocking way)?

The second problem. There are other combinations of accompanying errors and I'm not sure if I understand which are transient and which indicate message loss (and how to recognize it at all):
* error_cb: _TRANSPORT: some_ip:9092/bootstrap: Connect to ipv4#some_ip:9092 failed: No route to host
* error_cb: _NODE_UPDATE: some_hostname:9092/1: Broker hostname updated
* on_delivery REQUEST_TIMED_OUT
* on_delivery NOT_ENOUGH_REPLICAS
* on_delivery NOT_ENOUGH_REPLICAS_AFTER_APPEND
* error_cb: _MSG_TIMED_OUT: some_ip:9092/bootstrap: 1 request(s) timed out: disconnect 

The producer is set up the following way:
```python
#setup:
_producer = confluent_kafka.Producer(**{
    'client.id': client_id,
    'bootstrap.servers': bootstrap_servers,
    'log.connection.close': False,
    'api.version.request': True,
    'queue.buffering.max.messages': 100000,
    'queue.buffering.max.kbytes': 4000000,
    'queue.buffering.max.ms': 1000,
    'message.send.max.retries': 9000,
    'batch.num.messages': 10000,
    'delivery.report.only.error': True,
    'default.topic.config': {
        'request.required.acks': -1,
    },
    'error_cb': error_cb,
    'on_delivery': on_delivery,
})
atexit.register(_producer.flush)

#usage:
_producer.produce(topic, cPickle.dumps(value, KAFKA_PICKLE_PROTO))
_producer.poll(0)
```

**Comment by ewencp** [comment]
@fillest _UNKONWN_TOPIC is an internal error code for librdkafka that indicates an operation tried to use a topic that librdkafka doesn't know about. The message wouldn't even have been sent out at this point, so you'd need to retry it.

In general, retries will be applied except for permanent errors, so given your very large # of retries and the default backoff time of 100ms, you should generally only see errors if there is a sustained problem with your cluster. Regarding the individual errors:

* TRANSPORT: Indicates connections to the cluster can't even be made (as `No route to host`) would suggest. This is not even tied to an individual request.
* NODE_UPDATE: Indicates the hostname changed (e.g. maybe you moved a broker ID to a new host). This shouldn't cause any problems -- the old connection will be torn down and a new one initiated.
* REQUEST_TIMED_OUT: In an on_delivery, this means the data could not be written by the broker in the timeout specified in the produce request (i.e. the `request.timeout.ms` configuration)
* NOT_ENOUGH_REPLICAS: the message was completely rejected by the broker and has not been written at all because there aren't enough in sync replicas to satisfy the request.
* NOT_ENOUGH_REPLICAS_AFTER_APPEND: this means that the broker accepted the message and wrote it to it's own log because when the record reached the broker there were enough in sync replicas, but then one more more of the replicas disappeared and never replicated the data. In this case the data is written, but there is a risk of loss because it has been written to fewer replicas than requested. Of course, it also might be fine if the other replica came back up and continued replicating data again.
* MSG_TIMED_OUT: Indicates that it took too long to be processed (it may be in flight or may still just be buffered locally). The timeout for this is specified by `message.timeout.ms`.
