### ISSUE TITLE
We've experiencied a few messages lost

### ISSUE THREAD

**Issue by wesleysimbiose** [confluentinc/confluent-kafka-python#104]
confluent-kafka==0.9.2, librdkafka 0.9.2, kafka 0.10.1.0, Python 2.7.12

We run an API and sending messages to Kafka, when we run the following code we've experienced some messages lost, we check offsets of kafka and the offsets is less than expected.
In any moment is raising or logged any error or exception.

```python

 self._client = Producer(config_)

try:
    self._client.produce(topic, message)
except BufferError:
    self._client.poll(0)
    self._client.produce(topic, message)
```
config used on producer 
```json
        "message.send.max.retries": 5,
        "retry.backoff.ms": 100,
        "queued.min.messages": 1
```
We could fix the error calling flush after every message sent, with result a massive lost of performance.

```python
try:
    self._client.produce(topic, message)
    self._client.flush()
except BufferError:
    self._client.poll(0)
    self._client.produce(topic, message)
```

Is The correct approach ? what is the best way to avoid messages lost and not lost performance ?

## New Information

The messages that was lost, are the last ones, the producer do not guarantee that all messages are sent.

The workaround that fixed it without lost of performance was the following approach
```
atexit.register(self._client.produce.flush)
```

Is The correct approach ?

**Comment by edenhill** [comment]
Hi Wesley,

your analysis of the producer behaviour is correct.
Since the producer is asynchronous a produce() call will just enqueue the message on an internal queue and quickly return, the actual batching and transmission to the broker is performed by a background thread which also waits for brokers acknowledgements.
What this means in practice is that if you do:
```
 p.produce(topic,msg1)
 p.poll(0)
```
Then it is highly unlikely that msg1 will have been transmitted to the broker and an ack received by the time poll() is called so it will just return immediately with nothing done (timeout=0) and the message still in transit.

`p.flush()` simply calls `p.poll(..)` until **all** `produce()`d messages have been succesfully produced to broker, or failed. That's why you dont get any message loss when you call flush() on program exit.

Regarding BufferError:
the internal producer queue is limited by `queue.buffering.max.messages` (default 100K msgs), `queue.buffering.max.kbytes` (default 400 MB).
When either of these are reached the produce() will raise BufferError and it is common to backoff for some time and then try the message send again.

There is one important thing to note here: queue.buffering.max.* accounts not only for messages being transmitted to the broker, but also those that are already produced or failed but not had their delivery report callback called (if any). For this reason an application must call `p.poll(..)` at regular intervals to serve the "reply queue" of waiting acks/errors.

There are three typical ways to do this:
 * call poll(0) after each produce. also make sure to call poll() at regular intervals if your producer loop is idle so that previously sent messages' acks are delivered.
 * call poll(..) from a separate thread that only does polling
 * call poll(..) from your program's main loop.

**Comment by wesleysimbiose** [comment]
Thank you for your answer!

**Comment by telles-simbiose** [comment]
Hi, @edenhill ,

We tried what you suggested, but we still get `BufferError: Local: Queue full`.

We first called `poll(0)` right after calling `produce(...)`:

```python
    def _write_with_retries(self, message, topic):
        for _ in range(self._max_retries):
            try:
                self._client.produce(topic, message,
                                     callback=self.delivery_callback)
                self._client.poll(0)
                return
            except Exception as error:
                time.sleep(1)
                self._reconnect()
                raise error
        raise KafkaRouterException(
            "Reached maximum number of retries when writing message")
```

And then, we created a background scheduler to call `poll(..)` periodically:

```python
    self.scheduler.add_job(self._poll_job, 'interval', seconds=SECONDS_TO_CALL_POLL)
```

```python
    def _poll_job(self):
        self._client.poll(SECONDS_TO_CALL_POLL)
```


After our script running for enough time, we still get `BufferError`...

**Comment by telles-simbiose** [comment]
Update:

We got it to work by doing this (however, I am not aware of performance impacts it may have introduced):

```
    def _write_with_retries(self, message, topic):
        for _ in range(self._max_retries):
            try:
                try:
                    self._client.produce(topic, message,
                                         callback=self.delivery_callback)
                except BufferError:
                    self.flush()
                    self._client.produce(topic, message,
                                         callback=self.delivery_callback)
                return
            except Exception as error:
                time.sleep(1)
                self._reconnect()
                raise error
        raise KafkaRouterException(
            "Reached maximum number of retries when writing message")
```

**Comment by edenhill** [comment]
The flush approach will work but is quite drastic since it will wait for all messages in-queue to be delivered (which will negatively impact your thruput): and for the sake of the failing produce() call you only need to wait for one message to be delivered.
So I would suggest something like this instead:
```
while True:
    try:
       self._client.produce(..)
       break
     except BufferError:
        # Try again in 100ms or sooner if a delivery report is triggered
        self.poll(0.1)
        continue
```

**Comment by telles-simbiose** [comment]
I thought this approach wouldn't work, because I already added a thread that keeps `poll(..)`ing, but I will give it a try.

Thanks @edenhill !

**Comment by edenhill** [comment]
Oh, I'm sorry, I missed that.
Your poll-in-separate-thread approach should work, but your producer-thread code needs to retry in this case, now it seems to bail out and reconnect(??)

**Comment by telles-simbiose** [comment]
Well noticed @edenhill , but now I tried your poll-then-retry approach:

```python
        for _ in range(self._max_retries):
            try:
                self._client.produce(topic, message,
                                     callback=self.delivery_callback)
                break
            except BufferError:
                # Try again in 100ms or sooner if callback is triggered
                self._client.poll(0.1)
                continue
            except Exception as error:
                time.sleep(1)
                self._reconnect()
                raise error
        raise KafkaRouterException(
            "Reached maximum number of retries when writing message")
```

...but it exceeded our limit of 10 retries per message, so it took about 1s in only 1 message, I think it should be enough to free the buffer enough to send that 1 message. Maybe there is something wrong with `poll(..)`?
We are going to take a really high throughput in our application, so maybe any of these solutions would hurt it bad because of their blocking behaviour...

**Comment by telles-simbiose** [comment]
To give more details, we are using these producer configurations:

```json
{
        "message.send.max.retries": 5,
        "retry.backoff.ms": 100,
        "queued.min.messages": 1
}
```

**Comment by edenhill** [comment]
nit: `queued.min.messages` is a consumer property. What are you trying to achieve with that setting? `batch.num.messages` perhaps?

There really isn't any point in retrying sooner than poll() returns by its own means (e.g, not timeout) since a timeout indicates that none of the in-queue messages have been delivered and thus still no room in the internal queue.

**Comment by telles-simbiose** [comment]
Didn't notice this wrong configuration, maybe it has something to do with this issue?

If the approach using `poll` didn't work, but using `flush` worked, then maybe `poll` is not working as expected or my code should try more than 10 times to send the message, right?

**Comment by edenhill** [comment]
My point with regards to your poll() was that there is no point in retry producing a message until at least one delivery report has been called. Your poll() loop blocks for at most 100ms and then retries, regardless if there is actually any queue buffer space available.
Giving poll() more time increases the chance of a delivery during that wait-time, and thus increasing the chance that a retry might actually work.
What you have above is a hard retry-limit of 1 second (10 x 100ms), which is also the same as the default value of `queue.buffering.max.ms`.
I suggest increasing poll() timeout.

**Comment by telles-simbiose** [comment]
Got it, I will try it then, thanks!

**Comment by edenhill** [comment]
@telles-simbiose Any luck?

**Comment by telles-simbiose** [comment]
@edenhill , sorry for the delay!
Increasing the timeout indeed solved the problem, thanks so much for your help!
