### ISSUE TITLE
producer.flush() return message is unclear?

### ISSUE THREAD

**Issue by deeTEEcee** [confluentinc/confluent-kafka-python#1169]
In the docs, it states that flush actually returns an integer which represents "Number of messages still in queue." 

Does that mean I have to rerun flush in a loop until it returns 0?

**Comment by mhowlett** [comment]
if you want to be sure that the delivery status of all messages is known by your application, yes. if this number is > 0 messages in flight may or my not get been delivered.
note: you should only compare this number to 0 - the count accounts various types of events in a way that isn't documented very well.
note: typically you would only call flush when you exit your application, and poll otherwise to cause delivery handlers to execute. you might find this blog post useful: https://www.confluent.io/blog/kafka-python-asyncio-integration/

**Comment by deeTEEcee** [comment]
Thanks, that blog post is a bit useful.

> if you want to be sure that the delivery status of all messages is known by your application, yes. if this number is > 0 messages in flight may or my not get been delivered.
I wonder if this is true for 1.1.0 which we're running right now. It looks like it is since the comment indicating this fact does exist under that version.

**Comment by einarjohnson** [comment]
hi. i have a python application utilizing the `confluent-kafka-python`. this application is a long living process that fetches data from a database (inside a loop), processes them and posts messages to kafka using `confluent-kafka-python` and then it sleeps for a predefined time until the next iteration. would it be considered a bad practise to call flush at the end of each iteration of the loop? i am trying to enforce that all the messages have been delivered and persisted on the kafka topic at the end of each iteration.

**Comment by mhowlett** [comment]
if throughput is adequate for your needs, it's fine. poll and flush are very similar - the difference is flush will not exit until all outstanding delivery reports have been serviced (or the timeout is reached).

**Comment by einarjohnson** [comment]
thanks for such a quick response @mhowlett. so a code block like this should be fine?
```
    while True:
        try:
            messages = fetch_from_db()
            process_and_publish_to_kafka(messages)
        except:
            log.error("handle failure")
        finally:
            producer.flush()
            
        time.sleep(SLEEP_INTERVAL)
```
