### ISSUE TITLE
ImportError: DLL load failed while importing cimpl: with confluent Kafka python using windows

### ISSUE THREAD

**Issue by Kroosista** [confluentinc/confluent-kafka-python#1221]
Description
===========

Traceback (most recent call last):
  File "C:/Users/a681723/Downloads/confluent-kafka-python-master/confluent-kafka-python-master/src/confluent_kafka/serialization/x.py", line 26, in <module>
    from confluent_kafka import SerializingProducer
  File "C:\Users\a681723\Documents\VENV\lib\site-packages\confluent_kafka\__init__.py", line 40, in <module>
    from .deserializing_consumer import DeserializingConsumer
  File "C:\Users\a681723\Documents\VENV\lib\site-packages\confluent_kafka\deserializing_consumer.py", line 19, in <module>
    from confluent_kafka.cimpl import Consumer as _ConsumerImpl
ImportError: DLL load failed while importing cimpl: The specified module could not be found.

Process finished with exit code 1

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by sathwikcm** [comment]
Thank you. It worked.

**Comment by masariello** [comment]
Thanks. Yes, preloading librdkafka works. Could this be due to the fact that teh DLLs dependencies of the pyd are stored outside the module directory? I mean, is there a PEP that says that python ought to find those DLLs <py_dir>\..\confluent_kafka.lib ?

Imho, it would seem reasonable for python to enforce DLL dependencies to sit in the same directory as the PYD itself
