### ISSUE TITLE
After running the program for a long time, this error is reported "disconnected while requesting apiversion might be caused by incorrect security.protocol"

### ISSUE THREAD

**Issue by mzs0207** [confluentinc/confluent-kafka-python#1241]
Description
===========
The program starts up fine and after running for a long time, it suddenly reports the error mentioned above。Is it possible that the program is connecting to the kafka nodes through a proxy service and that the error is caused by one of the kafka nodes crashing?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @mzs0207 , can you please provide more logs?

**Comment by jliunyu** [comment]
Please feel free to reopen the issue with filling out the checklist and debug logs(add `"debug":"all"` to config) if you need more help.

**Comment by sagarmahar** [comment]
I have installed redpanda from official redpanda helm chart.
I am facing an issue while connecting to redpanda from a client

ERROR:
2024-02-13T14:33:06.35xx54Z
ERROR rdkafka:: client: librdkafka:
Global error:
BrokerTransportFailure (Local:
Broker transport failure):
172.xx.3x.1:31092/bootstrap:
Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener? or broker version is < 0.10 (see api.version.request)
after 1ms in state
APIVERSION QUERY, 5 identical errors) suppressed)

**Comment by sagarmahar** [comment]
Hi @jliunyu 
I have installed redpanda from official redpanda helm chart.
I am facing an issue while connecting to redpanda from a client

ERROR:
2024-02-13T14:33:06.35xx54Z
ERROR rdkafka:: client: librdkafka:
Global error:
BrokerTransportFailure (Local:
Broker transport failure):
172.xx.3x.1:31092/bootstrap:
Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener? or broker version is < 0.10 (see api.version.request)
after 1ms in state
APIVERSION QUERY, 5 identical errors) suppressed)
