### ISSUE TITLE
What does TRANSPORT error mean?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#128]
I get lots of these in my error_cb routine, (error -195), but then sometimes I get my on_delivery callback called, with no indication of an error. This suggests to me that the TRANSPORT error isn't really an error. Maybe it means we can't get through to all the brokers in the cluster, but only some of them? If it is not accompanied by an ALL_BROKERS_DOWN, can I safely ignore it?

**Comment by edenhill** [comment]
The TRANSPORT error represent connection errors with the broker, typically connection closed or connection refused.
The error_cb should give you more context through the error string.

If you are on osx this is typically caused by 'localhost' resolving to both ipv4 and ipv6 but the broker is only listening on one of those address families, in which case you can set 'broker.address.family': 'v4'.

But yes, you are correct, TRANSPORT errors can be ignored, they are typically transient.

**Comment by johnrgregg3** [comment]
OK. I'm running on Ubuntu. I used to log the string, but I seem to recall that sometimes it would hit me with an exception, so I stopped doing that. I'll put that back and see if I can reproduce it. If so, I'll post here. Thanks!

**Comment by davidblewett** [comment]
> But yes, you are correct, TRANSPORT errors can be ignored, they are typically transient.

I would appreciate updating the documentation as to what exceptions are transient and what are permanent. Even better, it would be very nice to encode that in the exception class hierarchy, so that people can have an exception handler for say `KafkaTransientException` that just logs it and moves on, and one for `KafkaPermanentError` that logs and triggers graceful shutdown.

**Comment by edenhill** [comment]
That's a good idea, @davidblewett . We'll look into it.

**Comment by kaigarabushi** [comment]
I have been extremely frustrated lately as vmware fusion systems that I have long used are now chronically failing with the "transport (VMDB) error -14 pipe connection has broken". Searching searching and nothing working I noticed this thread which may have nothing to do with my error but I have a vague feeling that updating root with OPEN CORE PATCHER on a Sonoma system alongside Mojave and Monterey - all of which now fail to load windows virtual systems with the same error ... may have triggered this nightmare. I am thinking I may have to replace the disk and start afresh with earlier patchers.
