### ISSUE TITLE
Make producer callback optional

### ISSUE THREAD

**Issue by wyfo** [confluentinc/confluent-kafka-python#1281]
Question
===========
As mentioned in #885, there is always a producer callback registered, allowing to execute `on_delivery` when provided. 
I doesn't know Kafka very well, but I've understand that we have to call `Producer.poll` after `Producer.produce` because of the callback registration. However, when `on_delivery` is never used at all, then calling `poll` would not be mandatory.

Could it be a good idea to add a `no_callback` boolean parameter to `Producer` which would prevent the callback to be added? As a side effect, when `no_callback=False`, using `on_delivery` by mistake should raise an error.

**Comment by jliunyu** [comment]
Hi @wyfo, thanks for asking. 

-> `However, when on_delivery is never used at all, then calling poll would not be mandatory.`
Even though don't set the deliver callback, you still need to call the poll() because the python client sets a delivery callback internally.

-> `Could it be a good idea to add a no_callback boolean parameter to Producer which would prevent the callback to be added? As a side effect, when no_callback=False, using on_delivery by mistake should raise an error.`
No_callback is not a good idea because you do need a delivery report callback, otherwise you have not idea about whether the message is delivered or not.
