### ISSUE TITLE
None errors on kafka consumer.poll()

### ISSUE THREAD

**Issue by ltagliamonte-dd** [confluentinc/confluent-kafka-python#1461]
Description
===========

I'm doing some testing on an app and I noticed that if i set a wrong topic name, just the topic name, when I perform a pool using the consumer i ONLY get the first time the error 
```
KafkaError{code=TOPIC_AUTHORIZATION_FAILED,val=29,str="Subscribed topic not available: <TOPIC_NAME>: Broker: Topic authorization failed"}
```
all the other poll call return msg=None with no error.

I'm expecting to receive an error every time I call poll, so that i can increment a prom counter to alert on poll failures.

How to reproduce
================

just set a wrong topic name and print the msg.error() returned by kafka_consumer.poll(2)

Checklist
=========
Please provide the following information:

 - confluent-kafka==1.9.2
 - Apache Kafka 2.8.2

**Comment by OneCricketeer** [comment]
The consumer client only periodically fetches topic metadata from the cluster, not on every poll

**Comment by ltagliamonte-dd** [comment]
Thank you for the answer @OneCricketeer, I think this is bit of strange behavior, if i have an authN/Z problem i'd like for the driver to raise an error every time i try to poll for a message.
in the logs of my application i saw the error 1 time, however in a busy logging situation that single error line can be easily missed and extend the debug time, what do you think?

**Comment by OneCricketeer** [comment]
Like I said, topic metadata, therefore auth, will only be done on a period greater than the poll intervals, by default. This isn't unique to Python, necessarily, it's to reduce overall network requests.

I do agree the error should probably be fatal, but I don't have any recommendations to catch/raise it as a fatal exception. One recommendation would be checking `message is None` since you're probably expecting at least a partition, offset, etc and nullable record keys/values would be in the respective attribute of the message

**Comment by pranavrth** [comment]
You can use `Consumer.assignment` to check if the given topic is assigned to the consumer yet or not.
