### ISSUE TITLE
Any way to control the number of threads that the library generates?

### ISSUE THREAD

**Issue by mtrienis** [confluentinc/confluent-kafka-python#179]
Hi,

I was wondering if there was a way to control the number of threads that this library generates? 

Also, what kind of upper bound is there in terms of the number of threads should we expect? 

Thanks, Mike.

**Comment by edenhill** [comment]
Hi Mike,

that's currently not possible.

librdkafka will create one internal main thread and one thread per broker.
If a bootstrap broker exactly matches (by name and port) an advertised broker it will be promoted to a real broker and the thread will be re-used, otherwise a new broker thread will be created.

So, best case: 1+N threads (N=brokers in cluster), worst case: 1+(N*2) if all brokers in cluster are specified as bootstrap but dont match (e.g., missing domain part, or using ip address or some alias).
(The port defaults to 9092 if not specified).

The per-broker thread design was meant to provide parallelism on modern hardware and is highly effective if partitions are evenly balanced across brokers.

Are you seeing a problem with the thread count?

**Comment by mtrienis** [comment]
No problems. I'm just gathering some information as we integrate your library with additional services.  

Thanks for your quick response!

**Comment by mtrienis** [comment]
Hi @edenhill , I guess in the Python world it's fairly easy to end up with quite a fewer workers / processes per server (especially if there are blocking calls: e.g. database requests). 

I was wondering if you've had any feedback on either the memory footprint or increases in context switches due to the number of threads for producers integrating this library?

**Comment by edenhill** [comment]
It is generally advised to reuse a Kafka client as far as possible since it is stateful and has a startup cost, the background threads adds overhead as well.
