### ISSUE TITLE
Reducing avro producer bandwidth 

### ISSUE THREAD

**Issue by idarlington** [confluentinc/confluent-kafka-python#222]
I noticed when messages are sent via avro producer the tproxy port (8081) receives between 2-2.38KB.

Is there a way to reduce this as it seems quite high.

Any suggestions @edenhill

**Comment by ewencp** [comment]
@idarlington Is this a question about the python client or the [REST Proxy](https://github.com/confluentinc/kafka-rest)?

**Comment by idarlington** [comment]
@ewencp the Python client.

**Comment by ewencp** [comment]
Oh, are you referring to when it connects to the schema registry? Much of that data should be the schema itself, though there is some overhead. How large is your schema?

Regardless, this should only happen the first time you send a message with a given schema, so on the whole this is pretty cheap compared to how much data you will presumably be sending with the producer.

**Comment by idarlington** [comment]
@ewencp  The file size is 6.2KB

**Comment by ewencp** [comment]
@idarlington Can you clarify more about your setup? I'm not sure what the sizes are that you're referring to. If you are referring to the interaction with the schema registry, I guess you mean that your schema is 6.2KB and the response is 2-2.5KB? That does sound like more than I would expect given that registration should only return the schema ID (plus the overhead of whatever HTTP headers are returned), but again, this request should happen once per process per schema, so it's very infrequent.

**Comment by idarlington** [comment]
@ewencp, Yes it is the interaction between the schema registry. The `.avsc` file is 6.2KB.

I thought it would be a one-time thing as well since the producer is initialized once. Messages are sent every 5 seconds from the device and viewing network traffic through `iftop` I see bandwidth usage of 2.38KB. It is an IOT device that occasionally uses mobile data so 2.38KB at each pulse interval could be costly.

**Comment by ewencp** [comment]
@idarlington That definitely seems odd since the schemas should be cached (send calls [encode_record_with_schema](https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/__init__.py#L64), which calls [register](https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/serializer/message_serializer.py#L98) on the cached schema registry client, which [checks the cache](https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/cached_schema_registry_client.py#L123)).

Are you using the same python schema object or is it getting reloaded? Maybe something with the hashing isn't working somehow, causing it to try to re-register every time? Can you share any code snippets that might help track down the issue?

**Comment by idarlington** [comment]
@ewencp you are right, after some refactoring, I noticed the schema from the schema registry is cached once it is called, the problem was with my code, it seems the schema object was getting reloaded.

Thanks.
