### ISSUE TITLE
How can i setup the consumer and producer on a live enviornment?

### ISSUE THREAD

**Issue by initiuminc1** [confluentinc/confluent-kafka-python#232]
We are using twitter stream to utilize the twitter data. our initial thought was demonising the python script for producer and consumer with a process management tool(like supervisor). 

Any other thoughts?

**Comment by mtrienis** [comment]
Yes, you can use supervisor. Another option is the multiprocessing library:
- https://docs.python.org/2/library/multiprocessing.html

**Comment by Gowtham95india** [comment]
I'm not sure how **multiprocessing** library is compared to  **supervisor**. 

I'm already running Node Js Kafka consumer in production environment and planning to switch to Python Confluent Kafka.  

I prefer the native ones rather than external tools.  So I prefer to do this with **systemd** rather than supervisor or monit even though both of the tools might have some advantage over systemd like memory limiting etc. 

Coming to code part, you can multiprocessing to leverage the benefits of cpu cores obviously. Give all the processors the same **Group Id**. 
So all of them will consume the different messages.
