### ISSUE TITLE
Producer.produce() lost message when the 100001 invoke 

### ISSUE THREAD

**Issue by lzhjie** [confluentinc/confluent-kafka-python#235]
first run 
start offset: 0
insert {'fail': 0, 'qps': 98916, 'sum': 100005, 'cost': 1.011}
search {'fail': 5, 'qps': 487829, 'sum': 100005, 'cost': 0.205}

second run
start offset: 100004  # ought be 100005
insert {'fail': 0, 'qps': 260429, 'sum': 100005, 'cost': 0.384}
search {'fail': 5, 'qps': 275495, 'sum': 100005, 'cost': 0.363}

**Comment by edenhill** [comment]
I'm sorry but there is simply nothing to go on here, please provide:
 * producer code
 * configuration
 * logs, if any
 * a proper description of the problem: what you are expecting to see, what actually happened.

**Comment by lzhjie** [comment]
I write a file for this [(https://github.com/lzhjie/confluent_kafka_test/blob/master/confluent_kafka_test.py)](url) 
I need to confirm if there is any loss of message.
There is no lost when produce 50000 times per session， and I tried serveral times.

**Comment by edenhill** [comment]
In your code you are not retrying when produce() fails (which is most likely due to Buffer full, I suggest you catch the specific exception).
Also note that flush() will wait for all queued messages to be delivered, you only need to wait until at least one is delivered to be able to retry, so I suggest using poll() instead.

**Comment by lzhjie** [comment]
thank you
