### ISSUE TITLE
Timestamp is not generated in the key for 0.10 compatibility

### ISSUE THREAD

**Issue by atharvai** [confluentinc/confluent-kafka-python#24]
the producer doesn't seem to add a timestamp to the producer record when working with 0.10.0.0 protocol. Actually I couldn't find a way to specify the protocol to use. 

Part of Kafka Config:
```
inter.broker.protocol.version=0.10.0.0
log.message.format.version=0.10.0.0
log.message.timestamp.type=CreateTime
```

Error from KafkaStreams:

```
Exception in thread "StreamThread-1" java.lang.IllegalArgumentException: Invalid timestamp -1
	at org.apache.kafka.clients.producer.ProducerRecord.<init>(ProducerRecord.java:60)
```

This means when I have a Kafka Streams application running, I need to use a `WallClockTimestampExtractor` which is not ideal. 
Not sure if the problem is on python client side or librdkafka side.

**Comment by edenhill** [comment]
Since the Kafka protocol (<=0.9) is not safely forwards compatible you will need to tell the Python client what version to use.
This is done through two configuration settings:
 * `broker.version.fallback=YOUR_BROKER_VERSION`
 * `api.version.request=true|false`

When using a Kafka 0.10 broker you only need to set `api.version.request=true`.
If you use Kafka broker 0.9 or 0.8 you should leave `api.version.request=false`(default) and set `broker.version.fallback` to your broker version, e.g `broker.version.fallback=0.9.0.1`.

More info here:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by atharvai** [comment]
Awesome. Thanks! Can we get that added to the readme in this repo? I think others might find this very useful.
