### ISSUE TITLE
Process assignment events without consuming messages

### ISSUE THREAD

**Issue by Traktormaster** [confluentinc/confluent-kafka-python#395]
Description
===========
I have a peculiar consumer group setup in which I need to **process** the assign/revoke **callbacks without consuming messages** necessarily.

In my application there are messages generated by different producers that belong to their respected priority group. There are huge bursts of new messages and the consumers have limited resources, so it is not possible to process all messages in real time. It would be enough to have the higher priority messages block the lower tiers until there are none left. To achieve this priority message routing, I make consumers for each priority group (topic) and read the messages from the highest priority consumer possible.

My problem arises when there are mulitple of these router processes. Each of them knows how much messages the consumers can receive in total in a minute, but they must know how many messages they need to produce **individually**. Here's a simple equation:
`number_of_messages_current_router_process_should_produce = number_of_messages_consumers_can_process_in_total * (partitions_assigned_to_current_router_process / total_number_of_partitions_of_router_processes)`

Since the number of partitions for the given topics are mostly static and there is no metadata fetching for it (yet) in this kafka python library, I get that from configuration which is mostly fine.

I have set up the consumers with on_assign and on_revoke callbacks to keep track of how many partitions I have, but those only update when poll() is called. However, since I do not want to consume messages from the lower priority consumers those will not update their assignment for extended periods of time. Overall the router processes end up producing half of what they should because the assignment of the lower priority consumers do not get processed. (even though they are actually assigned in the background)

How to reproduce
================
There is not much to be reproduced as the documentation clearly states that callbacks are processed during poll(). There is a new consume() method which also processes events but passing num_messages=0 to it will make it do nothing.

I've looked around a little in librdkafka and found that rd_kafka_poll() could do just what I want, but confluent-kafka-python sets up the consumers with rd_kafka_poll_set_consumer() that will redirect the main kafka events to the consumer's queue. In this setup the rd_kafka_poll() is not usable according to the documentation.

Even if another setup would be used the event list for rd_kafka_poll() does not include assignment events in the documentation. I'm guessing that could be because those events are tied to the consumer all the time, but I'm not sure.

In the end my question is:
**Is there a way or could there be a way to process the assignment events of a consumer without consuming any messages?**

Checklist
=========

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('0.11.4', 721920), ('0.11.4', 722175)
 - [ ] Apache Kafka broker version: 0.11.0.0
 - [ ] Operating system: Linux 4.16.13-2-ARCH SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux

**Comment by rnpridgeon** [comment]
@Traktormaster, just to ensure I understand you correctly you wish you flush all messages from higher priority queues prior to handling messages for lesser queues during high levels of production correct? 

Have you considered pausing lesser priority topics in a separate consumer group as opposed to lumping them all into one group? 

Rather than assigning and revoking partitions it may be wroth while tracking consumer lag on particular topic partitions overtime and taking action based on this. If you find that consumer lag on high priority topic partitions are growing you could simply suspend the lower priority topic partitions until you hit an EOF exception consuming the high priority topic partitions which remain in the assignment list. 

pause: https://docs.confluent.io/current/clients/confluent-kafka-python/index.html?highlight=pause#confluent_kafka.Consumer.pause

resume: https://docs.confluent.io/current/clients/confluent-kafka-python/index.html?highlight=pause#confluent_kafka.Consumer.resume

librdkafka statistics(partitions->consumer_lag specifically)
https://github.com/edenhill/librdkafka/wiki/Statistics

see stats_cb in the python docs as well: 

https://docs.confluent.io/current/clients/confluent-kafka-python/index.html?highlight=pause#configuration

Also is there a particular reason you are handling backpressure in the producer as opposed to relying on Kafka? Kafka will store the offsets up to the configured retention policy limits on the broker. Barring some resource constraint on the broker you should be able to produce with reckless abandon allowing the consumers to play catch up as necessary.

**Comment by Traktormaster** [comment]
@rnpridgeon I think you've got it right. Firstly thanks for pointing out the pause() and resume() methods. I've started working on this when they were not present and I've been too focused on the initial picture to notice they could be of use to me.

I'll elaborate on how my problem came to be: Prior to the pause()+resume() api I could not use a consumer to subscribe to let's say 4 topics, but consume from one of them until it reaches EOF and then move on to the next topic in order of priority. So as a workaround I made 4 individual consumers that I could poll() for messages on my discretion. This bloated up the consumption logic of the workers, so to isolate these functionalities I removed it from them and made it its own process. The workflow from `[initial producers]->[workers]` became `[inital producers]->[priority routers]->[workers]`.

With newly opened eyes, I can see that I can actually return to the original workflow by having the worker's consumer subscribe to the topics and pause() on all lower priority ones. After EOF is reached I resume() the next in line. If I get a message from a higher priority topic I will pause the active lower ones. With this setup the single conumer is always polled and my original question is no longer relevant.

I guess I need to keep track of the TopicPartitions I pause(). I also need to pause() or resume() topics based on on_assign and on_revoke callbacks.

Since I've got a very promising workaround, I'm closing my question.
Thank You!
