### ISSUE TITLE
Several event types per topic

### ISSUE THREAD

**Issue by saabeilin** [confluentinc/confluent-kafka-python#442]
Description
===========
There are lots of cases where "on Avro schema per topic" does not work. A good description of the cases and solutions available in Java library is provided here:
https://www.confluent.io/blog/put-several-event-types-kafka-topic/

However, the Python library has "subject = topic + key/value" hardcoded, and even the parameter name in `encode_record_with_schema` is called `topic`, not `subject`.

While this behavior could be overriden in subclasses, would be great to have "NameStrategies" compatible/similar to java client implementation.

**Comment by saabeilin** [comment]
@rnpridgeon No problem, that's already implemented in other libraries.

**Comment by soxofaan** [comment]
also see #401

**Comment by mhowlett** [comment]
the support angle is very valid, and maybe enough reason to justify deferring the feature until it will be less problematic with other CP system, but i think we need to ultimately allow for it. https://github.com/confluentinc/confluent-kafka-python/pull/401#issuecomment-445390539

**Comment by rnpridgeon** [comment]
Fair enough. I see your point and given that this will likely be coming to .NET in the near future as well I will reevaluate my decision. I think there are are a few supporting features that may need to come into the picture as well in order to do this truly effective. I need to wrap up 1.0 and a few other things but after that I will put some careful thought into how to make this work given the state of the Avro Python implementation. From there we can reevaluate the existing PRs and make a plan on how to proceed.
