### ISSUE TITLE
how to set the property max.poll.records in Kafka Consumer

### ISSUE THREAD

**Issue by datta90** [confluentinc/confluent-kafka-python#491]
Description
===========
Wanted to know if the current package supports setting of max.poll.records for Kafka Consumer.
I am facing issues while inserting data into Mysql as mysql insert fails with error too many connections.

In Java by setting the above property my consumer is working properly. But I want to do this in python

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` ('0.11.5', 722176) and `confluent_kafka.libversion()`): ('0.11.5', 722431)
('0.11.5', 722431)

 - [x] Apache Kafka broker version: 0.11
 - [ ] Client configuration: `{...}`
 - [x] Operating system: ubuntu 16.04.5 LTS 64 bit
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Consume() allows you to specify the number of message to return from the fetcher queue. 

https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.consume

That said this is very unlikely to be the source of you connection issues with mysql. Instead I would look to your mysql connection pool settings and/or make sure you aren't establishing a new connection per poll iteration. Also make sure you are closing your connections to MySql on failure/exit.

**Comment by datta90** [comment]
Should I use ( Consume() ) along with the poll function ?

**Comment by rnpridgeon** [comment]
Depends on how you are using the client. If all your messages are going to the same Mysql table you could use Consume to pull down a batch of messages then use a Bulk Insert to insert the entire batch at once. If you do this however you will want to disable auto offset commits since it will consider all messages in that batch committed once they transfer from the library to your application. 

This is actually an open area of debate. We are considering deprecating the batch oriented consume methods because of the confusion it causes with offset commits. If enough people have valid use cases for using it however we may end up just documenting how to handle commits instead.

**Comment by datta90** [comment]
ok but what if i change my database from mysql to an no-sql database like MongoDB or Cassandra 
do you think I still have to worry about the no of records that comes at a single fetch ?
. I have heard these databases don't have any issues inserting many records at once

**Comment by cricket007** [comment]
Is there some limitation preventing using Kafka Connect rather than implement database logic in a Python consumer?

**Comment by rnpridgeon** [comment]
Yes you could use `consume` to get a batch of messages and bulk insert them into the database of your choosing. I would manually commit the offsets after executing the insert though. That way if it fails you won't miss messages.  Take a look at the following wiki for more on offset management https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management. Note that `rd_kafka_offset_store` is simply `store_offsets` in the python binding. 

As @cricket007 pointed out though Connect seems like it may be a suitable solution for your problem.
