### ISSUE TITLE
confluent-kafka 1.0.0 is incompatible with avro-python3 1.9.0

### ISSUE THREAD

**Issue by hoesler** [confluentinc/confluent-kafka-python#610]
Description
===========

Since version 1.9.0 of avro-python3 [Schema.props](https://github.com/apache/avro/blob/3c76495e9524ef322726d03d7ee406be89e8fde0/lang/py3/avro/schema.py#L211) returns a `MappingProxyType` object which not json-serializable by default and leads to following exceptions:

```
...
  File "<venv>/lib/python3.7/site-packages/confluent_kafka/avro/__init__.py", line 80, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "<venv>/lib/python3.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 105, in encode_record_with_schema
    schema_id = self.registry_client.register(subject, schema)
  File "<venv>/lib/python3.7/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 214, in register
    body = {'schema': json.dumps(avro_schema.to_json())}
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type mappingproxy is not JSON serializable
```

To fix this, the registry client (and everything else) should use [`Schema.__str__`](https://github.com/apache/avro/blob/3c76495e9524ef322726d03d7ee406be89e8fde0/lang/py3/avro/schema.py#L218) to get the json representation instead of calling `json.dumps(avro_schema.to_json())`

**Comment by mpyatishev** [comment]
I have the same problem

**Comment by rnpridgeon** [comment]
Hm, so the proposed workaround does seem like the right move here given the current state of things. I feel this should be raised as a bug with Avro as well though. It's a bit odd for `to_json` not to return a json serializable object(without their custom encoder) and even more so to break API compatibility in a minor release.

**Comment by saabeilin** [comment]
@rnpridgeon Maybe at least specify the version in `extras_require`?

**Comment by mpyatishev** [comment]
Here is the issue in Avro Jira:
https://issues.apache.org/jira/browse/AVRO-2411?jql=project%20%3D%20AVRO%20AND%20component%20%3D%20python

**Comment by tyronegroves** [comment]
Can the version be pinned?

**Comment by magiciiboy** [comment]
I downgraded to avro-python3 version 1.8.2. And it works.

**Comment by infecto** [comment]
Has there been any traction as to what we want to do here? I have found a number of the changes in the upstream Apache Avro library to be fairly frivolous including this one. Would rather we have resolution to this sooner rather than later.

**Comment by test1370** [comment]
Did anyone found the solution for this. This is not working if i downgrade the version.

**Comment by andyr0id** [comment]
I was also experiencing this issue and the avro-python3 downgrade didn't fix the issue. I found a workaround by enhancing Field.to_json:

```
from avro.schema import Field

Field.to_json_old = Field.to_json

# Fixes an issue with python3-avro:
# https://github.com/confluentinc/confluent-kafka-python/issues/610
def to_json(self, names=None):
    to_dump = self.to_json_old(names)
    type_name = type(to_dump["type"]).__name__
    if type_name == "mappingproxy":
        to_dump["type"] = to_dump["type"].copy()
    return to_dump


Field.to_json = to_json
```

**Comment by rkabb** [comment]
@andyr0id  where did you make this change ?

**Comment by rkabb** [comment]
downgrading to 1.8.2 worked for me too

**Comment by bharkreader** [comment]
downgrading worked for me. Pro-tip, downgrade avro-python3, not avro. (reading is hard)

**Comment by rnpridgeon** [comment]
I think we are going to move towards supporting FastAvro exclusively as opposed to the current fallback model. Thoughts?

**Comment by jamesjrg** [comment]
fastavro can't deal with nested schemas inside a union like this, though it's maybe a pretty weird usage of unions:

"""[
    {
        "namespace": "FooNamespace",
        "name": "NestedRecord",
        "type": "record",
        "fields": [
        {
            "name": "Id",
            "type": "int"
        }
        ]
    },
    {
        "namespace": "FooNamespace",
        "name": "FooRecord",
        "type": "record",
        "fields": [
            {
                "name": "NestedField",
                "type": "FooNamespace.NestedRecord"
            }
        ]
    }
]"""

**Comment by jamesjrg** [comment]
Maybe some of this is wrong, these are my notes on trying to make a Python service work with Kafka + avro using confluent-python-kafka:

* fastavro refuses to read schemas where a union case name has the same name as its type, at least when that type is itself defined in the parent union, e.g. like:
[
 {
        "namespace": "MyNamespace",
        "name": "SharedName",
        "type": "record",
        "fields": [
....
        ]
    },
 {
        "namespace": "MyNamespace",
        "name": "MyRecordTypeTopic",
        "type": "record",
        "fields": [
            {
                "name": "Message",
                "type": [
                    {
                        "name": "SharedName",
                        "type": "MyNamespace.SharedName"
                    },
                    {
                        "name": "SomeOtherUnionCase",
                        "type": "record",
.....

I worked around this by changing the schema to inline record definitions where they had the same name as the field. Though this was some time ago now, I could misremember, and maybe it was actually some other issue that inlining fixed (e.g. maybe it doesn't like union cases with a custom type unless inlined, regardless of the name being shared?)

* avro-python3 was changed in a minor version such that calling to_json() on a schema produces an object that is not by the default json serializable, then in various places (e.g. schema registration, which is in turn automatically called when e.g. publishing events) confluent-python-kafka tries to serialize it with the default JSON serializer.  Furthermore as far as I can tell confluent-kafka-python explicitly depends on the more recent version even though it's broken (?) (https://github.com/confluentinc/confluent-kafka-python/blob/master/setup.py#L17), though maybe I missed something. I think Confluent are uninterested in PRs to fix this, maybe because they're considering rewriting to use fastavro everywhere, but this problem has been around for months so not sure when if ever that will happen.

https://github.com/confluentinc/confluent-kafka-python/issues/610

* the string representation of fastavro schemas uses namespaces in such a way that the Kafka schema registry server returns a bad schema error for some schemas, i.e. fastavro produces:

[{'type': 'fixed', 'name': 'MyNamespace.UUID', 'size': 16}, {'type': 'record', 'name': 'MyNamespace.Foo', 'fields': [{'name': 'Experience
....

which doesn't work, whilst avro-python3 produces:

[{"type": "fixed", "name": "UUID", "namespace": "MyNamespace", "size": 16}, {"type": "record", "name": "Foo", "namespace": "MyNamespace", "fields": [{"type":
....

which as far as I remember didn't work, though this was some time ago now so maybe I mis-remember.

* confluent-kafka-python has a bug whereby it tries to use fastavro then falls back to slow avro for deserializing messages, except if None is passed for the reader schema (a very common case, as this means you want to re-use the same schema as was used for writing) it tries to dereference the None, throws an exception, and falls back to slow avro anyway. I think Confluent are uninterested in PRs to fix this, maybe because they're considering rewriting to use fastavro everywhere, but this problem has been around for months so not sure when if ever that will happen.

* This isn't a bug, but it is very confusing: whilst confluent-kafka-python uses fastavro if it can for serializing and deserializing, the registry client only works with schemas parsed by avro-python3 because it calls to_json on the schema, a function that doesn't exist in fastavro. (As above this is now the wrong method to call even for avro-python3, though that's not relevant for this point). The confusing thing is that the registry client is automatically called by the AvroProducer class, and therefore the loads function in confluent-kafka-python uses avro-python3 not fastavro. Yet at the same time, the confluent Kafka code still uses fastavro for production, because after using the non-fast avro schema for cache lookup it then re-parses the schema a 2nd time and creates a lambda closure with a fastavro schema. 
 
* When investigating errors and googling, you have to be aware that these are all slightly different things:

- The Python package avro
- The Python package avro-python3
- The Python package fastavro
- The Python package kafka-python
- The Python package confluent-python-kafka
- The default Kafka client (for JVM-based languages)
- librdkafka (used by most Kafka clients, but not by the default client)

**Comment by dimon222** [comment]
Latest release is tied to 1.9.2.1 so it's no longer possible to downgrade. What to do?

**Comment by rhoban13** [comment]
> Latest release is tied to 1.9.2.1 so it's no longer possible to downgrade. What to do?

I tried then not pinning to 1.8.2 and ran into https://github.com/lsst-sqre/sqrbot-jr/issues/11.

**Comment by dimon222** [comment]
@rhoban13 I've just ended up rewriting my code to use SerializingProducer and DeserializingConsumer. It seems to be working just fine.

**Comment by choogeboom** [comment]
For posterity (anyone who is stuck on the legacy producers/consumers) here is a workaround:

```python
class MappingProxyEncoder(json.JSONEncoder):	
    # This is a hack to get around a bug in confluent-kafka	
    # https://github.com/confluentinc/confluent-kafka-python/issues/610	
    def __init__(self, *args, **kwargs) -> None:	
        super().__init__(*args, **kwargs)	
        self._base_default = json.JSONEncoder.default	
    def __enter__(self):	
        """Replaces JSONEncoder.default with a new function that can handle MappingProxyType"""	
        base_default = self._base_default	
        def default(s, obj):	
            if isinstance(obj, types.MappingProxyType):	
                return obj.copy()	
            else:	
                return base_default(s, obj)	
        json.JSONEncoder.default = default  # type: ignore	
    def __exit__(self, exc_type: Type[Exception], exc_val: Exception, exc_tb) -> bool:	
        """Returns JSONEncoder.default to its original state"""	
        json.JSONEncoder.default = self._base_default  # type: ignore	
        return True
```

Then whenever you are having trouble with this bug, just wrap the problematic code in a context block:

```python
with MappingProxyEncoder():
    do_the_thing()
```
