### ISSUE TITLE
Is produce() fully non-blocking?

### ISSUE THREAD

**Issue by fillest** [confluentinc/confluent-kafka-python#62]
I've read the documentation for confluent-kafka-python and librdkafka, but it is not very clear (after related experience with kafka-python package) if produce() is guaranteed non-blocking (except when configured for bounding the queue). I'm working on some latency-sensitive web app and I need to send some data into kafka without any blocking regardless of brocker downtime, re-election or whatever. So will this work with confluent-kafka-python or i need to add another level of queuing?

**Comment by edenhill** [comment]
It will work as is:
The produce() method is asynchronous (non-blocking) at all times (if the local queue is full (`queue.buffering.max.messages`) it will raise a BufferError exception).

Your application should call poll() at regular intervals to serve the on_delivery delivery report callback.

**Comment by fillest** [comment]
Good, thanks!
About `poll()` - do I need it just for reports or is it technically required? I mean if I'm interested in e.g. logging any errors only, is global `error_cb` enough or I still need to `poll` periodically?

Also, about termination - as producing is anync and the app can be stopped at any moment by e.g. deploy system, on stopping I need to wait for enqueued messages to be sent, so I need to use something like `atexit.register(producer.flush)`, right?

**Comment by edenhill** [comment]
Per-message errors are only provided through the delivery report callback (on_delivery), the error_cb is for more generic/global errors.

If you are only interested in delivery failures you can provide a global `on_delivery` callback in the Producer() config dict and also set `delivery.report.only.error`.
E.g.:
```
p = confluent_kafka.Producer({"bootstrap.servers": "thelot", "on_delivery": my_dr_cb, "delivery.report.only.error": True})
```

Regarding termination, you are absolutely right that you will need to wait for outstanding messages to be delivered, or fail and flush() is right method.
I havent tried using it in an atexit, but conceptually it should work, please report how it goes.

**Comment by fillest** [comment]
1) Yep, `atexit.register(producer.flush)` seems to work nicely (at least in normal circumstances). Probably worth adding a suggestion to the docs (`atexit` is not widely enough known)

2) I've seen some errors in the output but `error_cb` for them was called only on app shutdown and I use `atexit.register(producer.flush)`. Does it mean that calling poll is actually required for `error_cb`? How can I avoid it? I obviously need to properly log these errors but without calling poll (it's a web app and the sending code should not block; and I wanted to avoid spawning a python-level thread for this). Can I use `log_cb` in Python somehow?
Also, I've just thought: if these messages get printed later alltogether, then they were stored somewhere. Does this mean that if I don't `poll` periodically, I will get a memory leak? Can this be avoided? Probably by not setting `error_cb` (I hope in this case there is another way to log these messages in python)?

**Comment by edenhill** [comment]
1) +1: good to know!

2) All callbacks require some means of triggering them, which is either by `poll()` or `flush()` (and to some extent `consumer.close()`).
While librdkafka could spontaneously trigger these callbacks from its internal threads it would put the burden on thread semantics and locking on the application developer, something they might not be familiar with. So to save them from thelseves this choice was made that all callbacks are called in an application thread, and it is up to the application developer to decide when and where.
So I think your best choice is either a separate python thread that calls poll() (it will then also serve the delivery callbacks), or that you stick `poll(0)` calls here and there in-between other blocking calls.

The `log_cb` is currently not exposed to Python.

Callbacks, whatever they are: error_cb, delivery reports, etc, are queued internally in librdkafka until the application calls poll() (or similar interface that calls poll() underneath, such as flush()).
So there is no memory leak per say because the objects are still tracked, and if the producer or consumer instance is destroyed prior to serving all those callbacks with poll() they will be freed, thus not resulting in a memory leak.

**Comment by fillest** [comment]
>  So to save them from thelseves this choice was made

Well, yeah, that's a complex problem and probably your choice was optimal.

>poll(0)

I guess `poll` uses some kind of sleeping (even with zero), which has "at least" semantics in Linux + also I currently have no other convenient place to call it from except on each request after `produce()`, so I will go with an extra polling thread then.

>So there is no memory leak per say

Oh yes, I didn't mean internal memory leak, I meant a "logical" memory leak in my particular case when I didn't call `poll` at all.

**Comment by edenhill** [comment]
Actually it doesnt do any sleeping at all if you give it 0, all it does is grab a mutex, check a queue, and release the mutex. So it should be fairly cheap.
It is okay to call poll(0) after each produce call, the performance impact is negligible, if any.

**Comment by fillest** [comment]
Oh, that's great then, I'll try it.
Worth documenting too :)
