### ISSUE TITLE
Not able to Identify the producer in code.

### ISSUE THREAD

**Issue by sp1rs** [confluentinc/confluent-kafka-python#642]
Description
===========
I have initialized the broker but not able to identify the broker object in the `if` statement.
Version: 1.1.0
python: 3.6

How to reproduce
================
```
class TransactionNotificationTracker:
    """For logging the transaction data to Kafka"""
    broker = None

    @staticmethod
    def transact_notification_tracker(x: str) -> None:
        """Push transaction event to Kafka."""
        if not TransactionNotificationTracker.broker:
            TransactionNotificationTracker.broker = Producer({'bootstrap.servers': settings.KAFKA_SERVER_HOST})
        if TransactionNotificationTracker.broker and x:
            try:
                # data
                data = x
                TransactionNotificationTracker.broker.produce('transactions_tracker', data.encode('utf-8'))
                TransactionNotificationTracker.broker.flush()
                logger.log('info', ['TransactionNotificationTracker', 'transactions_tracker',
                                    'transaction push_to_kafka', data])
            except Exception as e:
                logger.log('critical', ['TransactionNotificationTracker', 'transactions_tracker',
                                        'Exception in push_to_kafka', data, e])
        else:
            logger.log('critical', ['TransactionNotificationTracker', 'transactions_tracker_not_initialized'])

```

The log which I am getting is `transactions_tracker_not_initialized`.
I tried running it on shell
```
>>> TransactionNotificationTracker.broker
<cimpl.Producer object at 0x7f48605d27b8>
>>> if TransactionNotificationTracker.broker:
...    print("SDF")
... 
>>> if not TransactionNotificationTracker.broker:
...    print("SDF")
... 
SDF

```

Somehow the `if` check is failing. Any idea.?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by rnpridgeon** [comment]
The `Producer` object does not implement ` __nonzero__` and returns 0 for  `__len__` since there are no messages in the produce queue. Had there been a message in the queue it would return the number of messages to be sent to Kafka and it would evaluate to true. 

Instead you should be explicitly checking if  TransactionNotificationTracker.broker is equivalent to `None`

i.e. 
`if TransactionNotificationTracker.broker is not None:`

`x` is a positional argument and thus required so there really is no reason to check if it's None here. I suspect you are actually concerned if the string is empty; if true you will need to test for that. 

Also I recommend the following blog post which does an excellent job explaining why you should never rely on `truthiness` 

https://itnext.io/you-shouldnt-use-truthy-tests-753b39ef8893
