### ISSUE TITLE
AvroConsumer consume batch deserialize

### ISSUE THREAD

**Issue by mac2000** [confluentinc/confluent-kafka-python#665]
After looking around it seems that AvroConsumer does not deserialize Avro messages when read batches, seems like we can deserialize them by hand by calling private method which is a hack

After looking to pull request about batch consuming also did not found anything about avro

**Comment by rnpridgeon** [comment]
This was actually left out intentionally due to the complications it can cause with offset commits. 

By default `enable.auto.commit` and `enable.auto.offset.store` are both set to true which means the application will automatically store the offset + 1 once the message is handed to the application. This opens you up to a situation where you may "miss" messages if your consumer fails or exits prior to processing the entire payload. 

In order to effectively use the batch processing api you should set `enable.auto.offset.store` set to false while keeping `enable.auto.commit` set to true. Then you can call `store_offsets` within your processing loop in order to advance the committed offset only after the message has been handled.

https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.store_offsets

**Comment by allenxiang** [comment]
@rnpridgeon The batch consuming is much needed in many cases for performance reasons, please implement this feature soon. We can deal with the offsets ourselves. Also a general recommendation, please align your APIs with Java clients as much as possible. Thanks.

**Comment by edenhill** [comment]
@allenxiang Can you elaborate on the performance aspects of a batch API?
The messages are already pre-fetched (in batches) to a local queue, the poll() call simply shaves off a message from that queue. In contrast to the Python interpreters speed and the cost of object creation, the single message poll calls should not pose a substantial performance loss.

**Comment by allenxiang** [comment]
Got it. Wasn't very clear if pre-fetched was used under the hood. In that case, please make a note somewhere in the doc and use this point to answer similar issues like #591. Thanks a lot.

**Comment by venthur** [comment]
> In order to effectively use the batch processing api you should set `enable.auto.offset.store` set to false while keeping `enable.auto.commit` set to true. Then you can call `store_offsets` within your processing loop in order to advance the committed offset only after the message has been handled.

@rnpridgeon this puzzles me, intuitively I'd rather turn `enable.auto.commit` off and manually `commit` the offsets after the message has been handled. Why is `store_offsets` to be preferred here?
