### ISSUE TITLE
rewind capability

### ISSUE THREAD

**Issue by jsikarin** [confluentinc/confluent-kafka-python#672]
Description
===========
I write a lot of programs involving Kafka. Most of these programs have a general format that looks like this 
1. obtain data from topic
2. process the data
3. send data to a different topic

Now lets say my program has a fault when processing the data for whatever reason. what I would like to due is reset the offset to the point where my program started collecting data. So what I would like my program to look like is something more like
1. obtain "starting offset" for consumer groupid
2.  read data from topic 
3. process data from topic
    a. if fault processing data
             i. reset offset to "starting offset"
             ii. exit program
    b. else 
             i. send processed data to new topic 

Is there a way to accomplish currently with the functions in this library?

**Comment by rnpridgeon** [comment]
Rather than querying the starting offset and then manually falling back to that point why not just hold off on committing your offsets until you have reached some sort of checkpoint. 

https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management

If after reading about consumer offset management you still wish to manually roll back to a specified index you can do so in a rebalance callback as described here. 
 
https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset
