### ISSUE TITLE
Consumer Stats Data Inconsistent

### ISSUE THREAD

**Issue by kasturichavan** [confluentinc/confluent-kafka-python#712]
Currently retrieved stats_cb partitions data snippet looks as follows:
Consumer 1 output:
`{'0': {'consumer_lag': -1, 'desired': False}, '1': {'consumer_lag': -1, 'desired': False}, '2': {'consumer_lag': 1501, 'desired': True}, '3': {'consumer_lag': 1503, 'desired': True}, '4': {'consumer_lag': -1, 'desired': False}, '5': {'consumer_lag': -1, 'desired': False}}`

Consumer 2 output: 
`{'0': {'consumer_lag': -1, 'desired': False}, '1': {'consumer_lag': -1, 'desired': False}, '2': {'consumer_lag': -1, 'desired': False}, '3': {'consumer_lag': -1, 'desired': False}, '4': {'consumer_lag': 1499, 'desired': True}, '5': {'consumer_lag': 1503, 'desired': True}}`

Consumer 3 output: 
`{'0': {'consumer_lag': 1490, 'desired': True}, '1': {'consumer_lag': 1499, 'desired': True}, '2': {'consumer_lag': -1, 'desired': False}, '3': {'consumer_lag': -1, 'desired': False}, '4': {'consumer_lag': -1, 'desired': False}, '5': {'consumer_lag': -1, 'desired': False}}`

> 1>  Does `desired=True` mean a partition thats assigned to current consumer gathering stats ??? 
Why is `consumer_lag = -1` for partitions that have `desired=False` while that partition has a lag? 
>  2> And consumer name received from stats_cb is same for all the consumers `mats-consumer#consumer-1` ? How can that be fixed ?
> 3> Is each partition always assigned to a consumer ? Or do we have to set anything specific in code ?
> 4> And does each consumer randomly reassign diff partition ? 

 - [ ] confluent-kafka-python : 0.11.5
 - [ ] Critical issue

**Comment by kasturichavan** [comment]
@edenhill

**Comment by edenhill** [comment]
1. desired=true typically means the local consumer is assigned to, or otherwise interested in, the partition at hand, while desired=false means nothing in the consumer or application is using this partition.
consumer_lag is only maintained for assigned partitions that the consumer is currently reading from.

2. The client name is based on the  ´client.id´ configuration property.

3. All subscribed topics' partitions should be assigned to the consumer members of a consumer group, yes.

4. The partition assignment is controlled by the ´partition.assignment.strategy´ configuration property, see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
