### ISSUE TITLE
Expand AdminClient to include all functionality of ccloud cli

### ISSUE THREAD

**Issue by jfinzel** [confluentinc/confluent-kafka-python#799]
This is a more holistic need related to: https://github.com/confluentinc/confluent-kafka-python/issues/734

We really need a full python kafka admin library that does all that `ccloud cli` does, which is very difficult to use and automate around.  Is that planned?  [KafkaAdminClient](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaAdminClient.html) is on the right track.  Are there plans to create an API such as this?

Thanks!

**Comment by rnpridgeon** [comment]
There are some discussions around how we might decouple the python Admin API from the underlying librdkafka implementation allowing us to iterate there a bit more rapidly. Ultimately it makes more sense for these features to exist in python than it does in C so that is where we want to be. I'll update this with further details once we have made a final decision.
