### ISSUE TITLE
confluent-kafka hangs forever without any exception on receiving message.

### ISSUE THREAD

**Issue by asmodeusgreen** [confluentinc/confluent-kafka-python#829]
When I tried to connect and fetch message from kafka it stuck on receiving message. 

settings = {
        'bootstrap.servers': 'k2ks:2181',
    'group.id': 'gd-123',
    'session.timeout.ms': 6000,
    'default.topic.config': {'auto.offset.reset': 'smallest'}
}
c = Consumer(settings)
tp = TopicPartition('tps', 0)
c.assign([tp])

try:
    while True:
        msg = c.poll(0.1)
        if msg is None:
            print('no msg')
            continue
        elif not msg.error():
            print('Received message: {0}'.format(msg.value()))
        elif msg.error().code() == KafkaError._PARTITION_EOF:
            print('End of partition reached {0}/{1}'
                  .format(msg.topic(), msg.partition()))
        else:
            print('Error occured: {0}'.format(msg.error().str()))

except KeyboardInterrupt:
    pass

finally:
    c.close()

**Comment by gabrielmancini** [comment]
+1

**Comment by edenhill** [comment]
v1.5.0 (in a month or so) will improve error reporting (some of it is currently suppressed unless an error_cb is specified).

But for this case it looks like you might be connecting to Zookeeper since the bootstrap.servers port is 2181, make sure that you specify a valid broker listener, not ZK.

You can troubleshoot this further by setting `'debug': 'broker'` in your client config dict .
