### ISSUE TITLE
Questions about serializing/deserialzing producer/consumer API stability

### ISSUE THREAD

**Issue by choudhary001** [confluentinc/confluent-kafka-python#857]
Description
===========
I was looking at the new serializing/deserialzing producer/consumer api and the docs mention that it is experimental at this stage. My requirements are similar to that of the serializing/deserializing producer/consumer however since the api is still marked as experimental, I am trying to implement some of these things as a wrapper api on top of confluent_kafka. I wanted to know what parts of the api, i can consider stable so that I can utilize/re-use the modules/code that is present here. For example, are the parts of the API present in confluent_kafka.serialization module stable?

**Comment by choudhary001** [comment]
Ping!

**Comment by mhowlett** [comment]
it is very close to stable. one thing that caused us to mark this as experimental was simply the naming of the the classes (`Serializing` prefix) - this is such an important part of the API, it should probably be present in the primary producer / consumer classes. Also, it was merged right at the last minute and because it's such a core feature, better to give it a bit more run time before calling it stable. It did get a lot of review time though, so it's very close.
