### ISSUE TITLE
Support for KIP-429: Incremental rebalancing

### ISSUE THREAD

**Issue by bry00** [confluentinc/confluent-kafka-python#894]
Implement support for [KIP-429: Incremental rebalancing](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol)

**Comment by prathap-pft** [comment]
Any idea when the release date is?

**Comment by mhowlett** [comment]
status update:
- we should have it fully reviewed/complete in librdkafka at the end of this week (though not merged on master initially since we're in the process of releasing 1.5.2). there will be a time period of a month or more after this where we soak test, and otherwise improve confidence in stability.
- I've mostly written the additions to the python binding in a local branch.

**Comment by prathap-pft** [comment]
> status update:
> 
> * we should have it fully reviewed/complete in librdkafka at the end of this week (though not merged on master initially since we're in the process of releasing 1.5.2). there will be a time period of a month or more after this where we soak test, and otherwise improve confidence in stability.
> * I've mostly written the additions to the python binding in a local branch.

Hi,
Thanks for the update. 
I am testing incremental cooperative rebalancing, is that stable on this branch. 

Thanks,
Prathap

**Comment by mhowlett** [comment]
it is almost stable in librdkafka on the mhowlett/coop-proto4 branch. that should be merged to edenhill/incrreb later this week. thatt will be in the 1.6 release and merged to master after the 1.5.2 release. we have not pushed the python binding changes to github yet. i will likely open a PR for that today or tomorrow.

**Comment by alonilon** [comment]
Hi everyone !
Just health-checking this thread, is this done and merged already ? Is it still open ?

Thanks !
alon
