### ISSUE TITLE
ProduceException, does it exist?

### ISSUE THREAD

**Issue by dmitrypolo** [confluentinc/confluent-kafka-python#911]
Description
===========
The doc-string for the `SerializingProducer` mentions an exception called `ProduceException` as shown below.
https://github.com/confluentinc/confluent-kafka-python/blob/624cdb8fe459b8910410f379cf2658c8d096436b/confluent_kafka/serializing_producer.py#L160
However this doesn't seem to be an actual class in the repository. What is the proper error we should be using besides the serialization errors?

`confluent_kafka` version `1.4.2`.

**Comment by rnpridgeon** [comment]
You are correct. Due to the asynchronous nature of the produce API you will most likely never see an exception raised by the produce call other than those pertaining to Serialization. Instead you will realize your producer errors in the form of delivery reports. 

It is technically possible though so this doc will need to be updated. In the event something exceptional does happen when producing(other than serialization errors) a KafkaException will be raised not a ProducerException. 

In the short-term we will fix the doc string. In the long term we will wrap this in a ProduceError as we do with ConsumeError.

**Comment by rnpridgeon** [comment]
https://github.com/confluentinc/confluent-kafka-python/pull/912

**Comment by dmitrypolo** [comment]
Thanks, this was helpful.

**Comment by dmitrypolo** [comment]
Closing this issue as the #912 was just merged.
