### ISSUE TITLE
Assignement Rebalance

### ISSUE THREAD

**Issue by malfonso0** [confluentinc/confluent-kafka-python#917]
Description
===========
hi, i have a topic, where i post my messages.. the processing of this messages can take from 1 minute to maybe 5 to 10 minutos.
i have configured this topic to have lot of partitions (100 can be less.. not important for the test case). in order to process the topic in paralel i have all my consumers with in the same group id.
This is hosted on aws.. in standby i have only one consumer..and a lag metric to scale and create more consumers dinamically.
the thing is.. first message arrive.. first consumer start the processing. if in the middle  more messages arrive ( it doesnt matter the amount) more consumers are created.. but.. those dont start processing right away... ( i have a log message saing try poll and waiting 1 second for next poll). so its seems that are no messages in the topic, but i know this is wrong. Then.. when the first consumer commit the work and start polling for messages again.. al my consumer start working.
i have debugged this.. and its seems, that the "re balancing/assignemnt" of the topic is done at that moment. As before.. if i check the assignemt for all those consumers is empty.

is this as expected? how could i "rebalance" partiions in the middle? i was thinking doing something on a thread in regular bases (30 seconds should be ok).. but didnt know what to do.. maybe call consumer poll?

my code is the tipical
conf = {    'bootstrap.servers': KAFKA_CLIENT,
                "queue.buffering.max.ms":1000, 
                "max.poll.interval.ms":30*60*1000,  # this is for the long running task
            }
    es_producer = confluent_kafka.Producer(**conf)

    #read_topics = [topic for topic in topics if READ_TOPICS in topic]
    conf = {    'bootstrap.servers': KAFKA_CLIENT, 
                'group.id': group, 
                "max.poll.interval.ms":30*60*1000,
                'default.topic.config': {
                    'auto.offset.reset': 'earliest',
                    "enable.auto.commit" : False
                },
                'auto.offset.reset': 'earliest',
                'enable.auto.commit': False
            }

    consumer = confluent_kafka.Consumer(**conf, on_commit=BaseConsumer_conf.commit_report) 
    consumer.subscribe(["^.*PROCESS$",])

How to reproduce
================

- [ ]  Crate a topic. at least 2 partitions, preferently 5 or more
- [ ] Create a first consumer.. with a long running task, can be a simple 2 or more minute delay
- [ ] send multiple messages
- [ ] create second consumer (same group).
- [ ] in consumers.. do some logs. like message arriving.. poll none and

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yep, that seems right. although librdkafka itself doesn't require a call to poll to handle a rebalance in the case no rebalance callback is specified, internally, the python client registers a rebalance callback (`Consumer_rebalance_cb`) regardless of whether `on_assign` and `on_revoke` callbacks are specified to the python client. so a group rebalance will block on the consumer calling poll.

to get around this, you could pause the consumer when you consume a message, and call poll in a backround thread (which won't return any messages because the consumer is paused), then resume again when you're finished processing. the calls are threadsafe.

a side effect of pause is that it flushes the message cache (in the future, we'll improve things so it doesn't). So make sure you also tune `queued.max.messages.kbytes` right down to avoid excess network use.

this is a bit awkward because the API was designed under the assumption that processing would be << session timeout. we probably want a better story here ...

**Comment by malfonso0** [comment]
thanks  matt for the quick  and detailed answer.

so i will do

1. once received and parsed the message.. will pause the consumer ( i need to check how.. but the way you say it, there should be a pause funcion :) .
2. start a thread that do consumer.poll.. every 30-60 seconds.. should be enough for spikes of new messages.
3. when processing is done. pause the thread.. then consumer.resume.

i didnt, understand your mentions for message cache.. i will try to read about that.

related to session timeout.. i know that my proceesing could be long.. but lower than half hour.. so i just put that value. In my first tests, without modifying the desafult sessions.. when i finish the processing and trying to do consumer.commit, it failed, ( with assignments empty).. so i read about this sessions timout... im quite new in kafka!

thanks again!

**Comment by malfonso0** [comment]
Hi.. so i updated the consumer...
this is my code

def assigns_update(consumers, producers):
   # poll consumers
    for consumer in consumers:
            msg = consumer.poll(0)
            if msg is not None:
                logger.critical("ESTO NO DEBERIA PASAR")
    # poll producers
    for producer in producers:
        producer.poll(0)

# function to pause and resume
def StopContinue(consumers, pause=True):
    for consumer in consumers:
        if pause:
            consumer.pause(consumer.assignment())
        else:
            consumer.resume(consumer.assignment())


i have a small timerthread class.. child of thread.. that can be started and paused
tthread = TimerThread(10, "Balancer",assigns_update, [consumer, ], [es_producer, ] )
#i only use 1 consumer, and 1 producer.. but i enabled more than one.. just in case

Then... the main looks something like


#here creation of consumer and producers.
.....

while True
      msg = consumer.poll(5)
      if msg is None or Errors(msg):
             continue:
     StopContinue([consumer])
      tthread.start()   
    # LOOONG PROCESS HERE
     Process(msg)

     StopContinue([self.consumer], pause=False)
     tthread.stop()  

    consumer.commit()

in the commit... i have the following error
cimpl.KafkaException: KafkaError{code=_NO_OFFSET,val=-168,str="Commit failed: Local: No offset stored"}

its seems everything (about pausing and resuming) looks oks.. and i got this error, but its seems that the commit is happening anyways..... any tought?
i need further tests to verify the later
thanks

**Comment by Coder-HJ** [comment]
Explanation from chatgpt of comment 
https://github.com/confluentinc/confluent-kafka-python/issues/917#issuecomment-661430747

librdkafka, the C library that powers confluent-kafka-python, doesn’t require a call to poll() to handle a rebalance as long as no specific rebalance callback (like on_assign or on_revoke) is set.
However, confluent-kafka-python always registers a rebalance callback (Consumer_rebalance_cb) internally even if you haven’t specified on_assign or on_revoke callbacks in your Python code. This means that the Python client will always expect a rebalance to occur when poll() is called.
Blocking on Poll During Rebalance:

Because of this internal Consumer_rebalance_cb callback, a group rebalance will block on poll(). In other words, if a rebalance is needed, it will only complete if the consumer regularly calls poll() to check in with Kafka.
If a consumer stops calling poll() (e.g., because it’s busy processing a message), the rebalancing process can get delayed or blocked until poll() is called again.
Workaround: Pausing the Consumer and Using Background Polling:

To avoid blocking rebalances while processing long messages, the suggested workaround is to:
Pause the consumer after fetching a message to prevent it from fetching more messages.
Run poll() in a background thread while the consumer is paused.
When the consumer is paused, poll() won’t return new messages but will still allow the consumer to communicate with Kafka and handle any pending rebalances.
Resume the consumer after finishing message processing so it can fetch new messages again.
This approach keeps the consumer in sync with the Kafka cluster and prevents the rebalance from being delayed, even if message processing takes longer than usual.

Side Effects of Pausing:

Message Cache Flushing: When you call pause() on a confluent-kafka-python consumer, it flushes the local message cache. This means that any prefetched messages in memory will be discarded.
Network Usage: Since pause() clears the message cache, resuming the consumer may cause it to refetch messages, potentially leading to higher network usage.
Tuning queued.max.messages.kbytes: To minimize excess network usage, it's recommended to lower the value of queued.max.messages.kbytes, which controls the maximum memory allocated for prefetched messages. Reducing this value ensures that the message cache size is small, so any messages that are flushed don't result in significant network overhead when refetched.
Design Limitations:

The Kafka client API was designed with the assumption that message processing would be very quick relative to the session timeout (the time within which a consumer needs to send heartbeats to Kafka).
When processing times are long, this design assumption doesn’t hold, leading to issues like delayed rebalancing.
The author suggests that a better solution might be needed in the future to handle these cases more gracefully, acknowledging that the current API makes this scenario a bit awkward.
