### ISSUE TITLE
log_level in config is not reducing logs

### ISSUE THREAD

**Issue by yechiel-optimalq** [confluentinc/confluent-kafka-python#957]
Description
===========
Hi, we are using latest confluent-kafka-python and we passed the logging handler of our app to the consumer and producer to pass on to LibrdKafka.
The problem is that we are getting a lot of errors ("disconnected" mainly ) that are spamming our monitoring logs.

The recommendation from Librdkafka was to reduce the logs by sending "log_level": 3 in the config of consumer and producer, so we did, but this doesn't seem to reduce the logs.

The logs we are seeing are:
"message": "FAIL [api-v1-b4c4974dd-mjbrj#producer-2] [thrd:sasl_ssl://****.westeurope.azure.confluent.cloud:9092/6]: sasl_ssl://******.westeurope.azure.confluent.cloud:9092/6: 1 request(s) timed out: disconnect (after 801570ms in state UP, 1 identical error(s) suppressed)",
  "time": "2020-09-22T15:20:21.403325"

Not sure if we are doing something wrong. i verified and i see the log_level parameter passed to the producer and consumer.

How to reproduce
================
Use confluent cloud on Azure, run consumer , config:
 
auto.offset.reset = "earliest"
bootstrap.servers = "***.azure.confluent.cloud:9092"
client.id = "consumer-v1-client-1"
enable.auto.commit = false
fetch.wait.max.ms = 1000
group.id = "Ghod_consumer_group"
log_level = 3
queued.max.messages.kbytes = 10240
queued.min.messages = 1000
sasl.mechanisms = "PLAIN"
sasl.password = "***"
sasl.username = "****"
security.protocol = "SASL_SSL"
socket.keepalive.enable = true

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
Latest confluent python 

 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
Ubuntu (docker)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by yechiel-optimalq** [comment]
Latest

**Comment by edenhill** [comment]
This looks like the problem with Azure load balancers that kill connections without sending RST.
https://github.com/edenhill/librdkafka/issues/2845#issuecomment-625433415

**Comment by yechiel-optimalq** [comment]
Yes, i also provided a workaround from confluent that actually worked:
https://github.com/edenhill/librdkafka/issues/3077

But the error here is more about the log_level config not working for me in reducing the logs.

**Comment by mhowlett** [comment]
sys log level 3 == error, so you will still get error level messages having set that to 3. it seems that maybe the errors are originating from somewhere other than https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L623, which is what the info you're reading is referring to i think (i was only guessing that since you didn't give full text of the error).

it's debatable whether you should pass librdkafka error level logs onto your monitoring system as error level. they don't directly mean something has gone wrong with your application logic, and librdkafka will recover from anything it's possible to recover from. maybe just pass them on as warning.

@edenhill may have other commentary. generally, i think we have some things to tidy up re: error terminology in librdkafka for better UX.
